import type {Metadata} from 'next';
import {Poppins} from 'next/font/google';

import './global.css';
import {cn} from "@/utils";
import {Navbar} from "@/components/Navbar";
import {Footer} from "@/components/Footer";
import {Providers} from "@/components/Providers";

const poppins = Poppins({
    weight: ['400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon.ico', // /public path
    },
}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className="h-full">
        <body className={cn("relative h-full font-sans antialiased", poppins.className)}>
        <main className="relative flex flex-col min-h-screen">
                <Navbar/>

                <div className="flex-grow flex-1">
                    {children}
                </div>

                <Footer/>
        </main>
        </body>
        </html>
    )
}
